version: "3.8"

name: mongo-shop-db

services:
  auth-db:
    image: mongo
    container_name: auth-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - auth-data:/data/db
  item-db:
    image: mongo
    container_name: item-db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - item-data:/data/db

  player-db:
    image: mongo
    container_name: player-db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - player-data:/data/db

  inventory-db:
    image: mongo
    container_name: inventory-db
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - inventory-data:/data/db

  payment-db:
    image: mongo
    container_name: payment-db
    ports:
      - "27021:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - payment-data:/data/db

volumes:
  auth-data:
  item-data:
  player-data:
  inventory-data:
  payment-data: