// Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: modules/auth/authPb/authPb.proto

package go_microservices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structures
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{0}
}

type AccessTokenSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenSearchReq) Reset() {
	*x = AccessTokenSearchReq{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenSearchReq) ProtoMessage() {}

func (x *AccessTokenSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenSearchReq.ProtoReflect.Descriptor instead.
func (*AccessTokenSearchReq) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{1}
}

func (x *AccessTokenSearchReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type AccessTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessTokenRes) Reset() {
	*x = AccessTokenRes{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenRes) ProtoMessage() {}

func (x *AccessTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenRes.ProtoReflect.Descriptor instead.
func (*AccessTokenRes) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{2}
}

func (x *AccessTokenRes) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type RolesCountEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesCountEmpty) Reset() {
	*x = RolesCountEmpty{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesCountEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountEmpty) ProtoMessage() {}

func (x *RolesCountEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountEmpty.ProtoReflect.Descriptor instead.
func (*RolesCountEmpty) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{3}
}

type RolesCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesCountReq) Reset() {
	*x = RolesCountReq{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountReq) ProtoMessage() {}

func (x *RolesCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountReq.ProtoReflect.Descriptor instead.
func (*RolesCountReq) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{4}
}

type RolesCountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolesCountRes) Reset() {
	*x = RolesCountRes{}
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolesCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesCountRes) ProtoMessage() {}

func (x *RolesCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_auth_authPb_authPb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesCountRes.ProtoReflect.Descriptor instead.
func (*RolesCountRes) Descriptor() ([]byte, []int) {
	return file_modules_auth_authPb_authPb_proto_rawDescGZIP(), []int{5}
}

func (x *RolesCountRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_modules_auth_authPb_authPb_proto protoreflect.FileDescriptor

const file_modules_auth_authPb_authPb_proto_rawDesc = "" +
	"\n" +
	" modules/auth/authPb/authPb.proto\"\a\n" +
	"\x05Empty\"8\n" +
	"\x14AccessTokenSearchReq\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"*\n" +
	"\x0eAccessTokenRes\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid\"\x11\n" +
	"\x0fRolesCountEmpty\"\x0f\n" +
	"\rRolesCountReq\"%\n" +
	"\rRolesCountRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2|\n" +
	"\x0fAuthGrpcService\x12;\n" +
	"\x11AccessTokenSearch\x12\x15.AccessTokenSearchReq\x1a\x0f.AccessTokenRes\x12,\n" +
	"\n" +
	"RolesCount\x12\x0e.RolesCountReq\x1a\x0e.RolesCountResB+Z)github.com/chakornpat-tn/go-microservicesb\x06proto3"

var (
	file_modules_auth_authPb_authPb_proto_rawDescOnce sync.Once
	file_modules_auth_authPb_authPb_proto_rawDescData []byte
)

func file_modules_auth_authPb_authPb_proto_rawDescGZIP() []byte {
	file_modules_auth_authPb_authPb_proto_rawDescOnce.Do(func() {
		file_modules_auth_authPb_authPb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_auth_authPb_authPb_proto_rawDesc), len(file_modules_auth_authPb_authPb_proto_rawDesc)))
	})
	return file_modules_auth_authPb_authPb_proto_rawDescData
}

var file_modules_auth_authPb_authPb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_modules_auth_authPb_authPb_proto_goTypes = []any{
	(*Empty)(nil),                // 0: Empty
	(*AccessTokenSearchReq)(nil), // 1: AccessTokenSearchReq
	(*AccessTokenRes)(nil),       // 2: AccessTokenRes
	(*RolesCountEmpty)(nil),      // 3: RolesCountEmpty
	(*RolesCountReq)(nil),        // 4: RolesCountReq
	(*RolesCountRes)(nil),        // 5: RolesCountRes
}
var file_modules_auth_authPb_authPb_proto_depIdxs = []int32{
	1, // 0: AuthGrpcService.AccessTokenSearch:input_type -> AccessTokenSearchReq
	4, // 1: AuthGrpcService.RolesCount:input_type -> RolesCountReq
	2, // 2: AuthGrpcService.AccessTokenSearch:output_type -> AccessTokenRes
	5, // 3: AuthGrpcService.RolesCount:output_type -> RolesCountRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_auth_authPb_authPb_proto_init() }
func file_modules_auth_authPb_authPb_proto_init() {
	if File_modules_auth_authPb_authPb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_auth_authPb_authPb_proto_rawDesc), len(file_modules_auth_authPb_authPb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_auth_authPb_authPb_proto_goTypes,
		DependencyIndexes: file_modules_auth_authPb_authPb_proto_depIdxs,
		MessageInfos:      file_modules_auth_authPb_authPb_proto_msgTypes,
	}.Build()
	File_modules_auth_authPb_authPb_proto = out.File
	file_modules_auth_authPb_authPb_proto_goTypes = nil
	file_modules_auth_authPb_authPb_proto_depIdxs = nil
}
